pipeline:
  name: Build Harness
  identifier: Build_Tejasps07_Harness_1712067879807
  projectIdentifier: Harness_POC
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: harness_run
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |-
                      cd UI_Web_Automation_Cucumber_BDD
                      curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
                      sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
                      sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
                      sudo rm microsoft.gpg
                      sudo apt update && sudo apt install microsoft-edge-stable
                      mvn test
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: Tejasps07/Harness
        build: <+input>
